"use strict";

let constants = require("constants"),
	mmh3 = require("murmurhash3js").x86.hash32,
	path = require("path"),
	fs = require("fs"),
	http = require("http"),
	https = require("https"),
	mime = require("mime"),
	moment = require("moment"),
	os = require("os"),
	zlib = require("zlib"),
	defaultConfig = require(path.join(__dirname, "../config.json")),
	dtrace = require("dtrace-provider"),
	precise = require("precise"),
	util = require("keigai").util,
	array = util.array,
	clone = util.clone,
	csv = util.csv,
	delay = util.next,
	defer = util.defer,
	iterate = util.iterate,
	lru = util.lru,
	number = util.number,
	merge = util.merge,
	parse = util.parse,
	json = util.json,
	string = util.string,
	ALL = "all",
	LOGGING = false,
	STALE = 60000,
	VERBS = ["delete", "get", "post", "put", "patch"],
	LOGLEVEL;
